### ISSUE TITLE
[Bug - Low Priority] Inconsistency on site ranks page

### ISSUE THREAD

**Issue by Cash120** [TranscendenceGN/TGN-Spigot#21]
On the about page in the ranks section under Guide, the requirements say that anyone apprentice and up can apply for guide. However, under Adept, it says that adept is the lowest rank that people can apply to be guide.

EDIT: added priority to the title because Labels gear was missing and I couldn't set one.

**Comment by Starza4TW** [comment]
Fixed! Danka Cash!
